import type { Metadata } from 'next';
import localFont from 'next/font/local';

import './globals.css';

const suit = localFont({
    src: [{ path: '../fonts/SUIT-Variable.woff2', weight: '100 900' }],
    variable: '--font-suit',
    display: 'swap',
});

export const metadata: Metadata = {
    title: 'hyun\'s devlog',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={`${suit.variable} antialiased`}>{children}</body>
        </html>
    );
}
