import { GoogleAnalytics } from '@next/third-parties/google';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { Space_Grotesk } from 'next/font/google';

import Providers from '@/app/providers';
import SessionInitializer from '@/components/auth/SessionInitializer';
import './style/globals.css';

const suit = localFont({
    src: [{ path: '../fonts/SUIT-Variable.woff2', weight: '100 900' }],
    variable: '--font-suit',
    display: 'swap',
});

const spaceGrotesk = Space_Grotesk({
    variable: '--font-space',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: "hyun's devlog",
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={`${suit.variable} ${spaceGrotesk.variable} antialiased`}>
                <Providers>
                    <SessionInitializer />
                    {children}
                </Providers>
                <GoogleAnalytics gaId={process.env.NEXT_PUBLIC_GA_ID!} />
            </body>
        </html>
    );
}
